# Generated by Django 5.1.6 on 2025-02-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
